# The PL-DDR wrapper asserts sys_resetn_sync asynchronously from calibration,
# UI-reset and board-reset sources, then releases it synchronously on aclk.
# Recovery/removal is guaranteed by the two-stage synchronizer; treating the
# asynchronous assertion arc as an ordinary setup path creates a false
# mmcm_clkout0 -> PL_CLK0_200M violation.
set ddr_reset_sync_clr_pins [get_pins -hierarchical -quiet -filter {
  REF_PIN_NAME == CLR && NAME =~ *sys_resetn_sync_reg*/CLR
}]
set_false_path -to $ddr_reset_sync_clr_pins

# Core and DMA are generated by independent MMCM output branches.  All traffic
# between them uses the explicit asynchronous FIFOs in
# gqav5_axi_row_mover_256_cdc; reset/error indications use two-flop
# synchronizers.  Timing the two domains as related fabric clocks incorrectly
# constrains the synchronizer first stages and reports impossible 0.1 ns setup
# requirements at 230/300 MHz, 240/300 MHz, and the 235/300 MHz release point.
set core_pl_clocks [get_clocks -quiet -filter {
  NAME =~ clk_core_*_unbuf
}]
set dma_pl_clocks [get_clocks -quiet -filter {
  NAME =~ clk_dma_*_unbuf
}]
set_clock_groups -asynchronous \
  -group $core_pl_clocks \
  -group $dma_pl_clocks

# Keep explicit directional exceptions as well as the clock-group declaration.
# Some block-design IP XDC files are parsed after this system XDC and can cause
# Vivado 2024.2 to retain paths into the first stages of the custom
# synchronizers in the timing graph.  The implementation hook reapplies and
# audits the same exceptions after all scoped IP constraints are loaded.
set_false_path -from $core_pl_clocks -to $dma_pl_clocks
set_false_path -from $dma_pl_clocks -to $core_pl_clocks

# Constrain the actual first-stage synchronizer endpoints explicitly.  This is
# narrower than a blanket datapath exception and preserves timing from every
# synchronizer first stage into its second stage, which is required for useful
# metastability-resolution analysis.
set accelerator_cdc_sync1_d_pins [get_pins -hierarchical -quiet -filter {
  REF_PIN_NAME == D &&
  NAME =~ *gqav7_accelerator_0*sync1_q_reg*/D
}]
set_false_path -to $accelerator_cdc_sync1_d_pins
